name: Deploy Spendoo-ai-backend

on:
  push:
    branches: [develop, dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t josephsameh/spendoo-ai-backend:latest .

      - name: Push Docker image
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker push josephsameh/spendoo-ai-backend:latest

      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull josephsameh/spendoo-ai-backend:latest
            docker stop spendoo-ai-container || true
            docker rm spendoo-ai-container || true
            docker run -d --restart=always --name spendoo-ai-container -p 8000:8000 \
              -e GROQ_API_KEY="${{ secrets.GROQ_API_KEY }}" -e SPENDOO_DEPLOY="${{ secrets.SPENDOO_DEPLOY }}" -e SPENDOO_ALLOWED_IP="${{ secrets.SPENDOO_ALLOWED_IP }}" josephsameh/spendoo-ai-backend:latest
            docker image prune -f